apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: songs-service
  template:
    metadata:
      labels:
        app: songs-service
    spec:
      containers:
        - name: songs-service-container
          image: europe-central2-docker.pkg.dev/lithe-aileron-486115-t3/microservices-repo/music-service:v1
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://10.98.96.3:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ";djZ9E^9_<U}9M^<"

            # --- RABBITMQ ---
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"

            - name: SERVER_PORT
              value: "8088"
            - name: SPRING_LIQUIBASE_ENABLED
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: songs-service-svc
spec:
  selector:
    app: songs-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP
