spring.application.name=linguaBoost

# DATABASE
spring.datasource.driver-class-name=org.postgresql.Driver
# Якщо змінної SPRING_DATASOURCE_URL немає, підставиться локальний localhost
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/music_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# LIQUIBASE
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# RABBITMQ
# У Kubernetes хостом буде назва сервісу (наприклад, rabbitmq-svc)
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# SERVER
server.port=${SERVER_PORT:8088}

# BUSINESS LOGIC (можна лишити без змін, якщо вони статичні)
spring.rabbitmq.queueName=email_queue
spring.rabbitmq.exchangeName=exchangeName